[package]
name = "concordium-lsp"
version = "0.1.0"
description = "Liquid Staking Platform for Concordium blockchain"
edition = "2021"

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
spl-token = { version = "3.1", features = ["no-entrypoint"] }
bincode = "1.3.3"
