pub enum CommonError {
    WrongReserveOwner,
    NonEmptyReserveData,
    InvalidInitialReserveLamports,
    ZeroValidatorChunkSize,
    TooBigValidatorChunkSize,
    ZeroCreditChunkSize,
    TooBigCreditChunkSize,
    TooLowCreditFee,
    InvalidMintAuthority,
    MintHasInitialSupply,
    InvalidOwnerFeeState,
    InvalidProgramId = 6116,
    UnexpectedAccount = 65140,
    CalculationFailure = 51619,
    AccountWithLockup = 45694,
    NumberTooLow = 7892,
    NumberTooHigh = 7893,
    FeeTooHigh = 4052,
    FeesWrongWayRound = 4053,
    LiquidityTargetTooLow = 4054,
    TicketNotDue = 4055,
    TicketNotReady = 4056,
    WrongBeneficiary = 4057,
    StakeAccountNotUpdatedYet = 4058,
    StakeNotDelegated = 4059,
    StakeAccountIsEmergencyUnstaking = 4060,
    InsufficientLiquidity = 4205,
    InvalidValidator = 47525,
}
